### ISSUE TITLE
Beyond the value range of arg_opts and file_opts.opti in config.c

### ISSUE THREAD

**Issue by qdzhaov** [mintty/mintty#1247]
I File config.c,the type of variable arg_opts and file_opts.opti is uchar,value range is 0-255,but arraysize of options is 269,bigger than 255,so some options in configfile will be error on save.

static struct {
  char * comment;
  **uchar** opti;
} file_opts[lengthof(options) + MAX_COMMENTS];
static **uchar arg_opts**[lengthof(options)];

**Comment by Biswa96** [comment]
It was probably fixed in this commit https://github.com/mintty/mintty/commit/c3745597350bc4cf6f2101471594e0382ecee8b9

**Comment by qdzhaov** [comment]
but arg_opts not fixed

**static uchar arg_opts[lengthof(options)]**

**Comment by ak2** [comment]
Funny such a long-standing issue should come up twice in a couple of days. Thanks for spotting that arg_opts was affected too.

**Comment by mintty** [comment]
Released 3.7.1.
