### ISSUE TITLE
"Show bold as colour" behavior changed

### ISSUE THREAD

**Issue by pktunit** [mintty/mintty#459]
Version: mintty 2.0.2 (x86_64-pc-cygwin)
Fonts affected: Lucida Console, 9-point

When using Lucida Console with the following settings:
"Show bold as colour" = CHECKED
"Show bold as font" = UNCHECKED
This used to only apply the bold colour. Now it applies the colour and emboldens the text. It would be nice to be able to go back to the old behavior.

Update: 
When using Consolas, if I select "Show bold as colour" and Show bold as font" it does apply the behavior I prefer, which is to show the bold font color without modifying the font weight.

Thanks!

**Comment by mintty** [comment]
It's a side effect of a fix of bold display for uncoloured characters which were not boldened at all when "bold as font" was off.
I'll try to find a common fix for all cases but the current situation is better than the one before, so I shouldn't simply revert. Some patience please.

**Comment by mintty** [comment]
Should be fixed in next release.

**Comment by pktunit** [comment]
Great! Thanks for the awesome work! =)

**Comment by matsaman** [comment]
This seems still broken with mintty-2.7.7 via cygwin. "Bold" text is wider & bolder, but I only want it to be brighter in color.

**Comment by mintty** [comment]
Please check your configuration (and consult the manual). If you provide your config file here (preferably stripped down), I can check what's going on.

**Comment by mintty** [comment]
Released 2.9.1.
